
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydata?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  cache:
  #    type: redis
  #    cache-names:
  #      - redis-cache
  #    redis:
  #      use-key-prefix: true
  #      key-prefix: "app@reids-cache:"
  #      time-to-live: 3m
  #      cache-null-values: true
  redis:
    host: localhost
    port: 6379
    password: 123456
    # 读超时时间，单位毫秒
    timeout: 1000
    # 数据库编号
    database: 0
    lettuce:
      #关闭超时时间；单位毫秒
      shutdown-timeout: 1000
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池最大连接数（使用负值表示没有限制,不要配置过大，否则可能会影响redis的性能）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）；单位毫秒
        max-wait: 1000

mybatis:
  type-aliases-package: com.cent.demo.myredis.dao
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: debug
    com.cent.demo.myredis.mapper: debug

redis:
  key-prefix:
    app-name: "app@demo-redis:"