
server:
  port: 8080

spring:
  application:
    name: myrabbit
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: myrabbit
    username: guest
    password: guest
    connection-timeout: 1m
    publisher-confirm-type: correlated
    publisher-returns: true
#    template:
#      mandatory: true
#      receive-timeout: 10000
    listener:
      simple:
#        注意manual可能会阻塞队列，影响消费，特别要避免无限消息循环阻塞（一直重回队头），考虑超限不入队或进死信队列
#        acknowledge-mode: manual
        concurrency: 4
        max-concurrency: 10
        prefetch: 10
#        消费异常可重试
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000

logging:
  level:
    com.cent.demo.myrabbit: debug